version: "3"
services:
  elasticsearch:
    build: elastic24/
    image: docker.elastic.co/elasticsearch/elasticsearch:2.4.6
    container_name: elasticsearch-liferay
    ports:
      - "9300:9300"
      - "9200:9200"
    volumes:
      - "./elastic24/config:/usr/share/elasticsearch/config"
      - "./elastic24/esdata:/usr/share/elasticsearch/data"
    networks: ['elasticstack']

  kibana:
    build: kibana46/
    image: docker.elastic.co/kibana/kibana:4.6.5
    container_name: kibana-liferay
    ports:
      - "5601:5601"
    networks: ['elasticstack']
    depends_on:
      - elasticsearch

  logstash:
    # Default Docker File Override to update / install plugins
    build: logstash24/
    image: logstash:2.4.1
    container_name: logstash-liferay
    ports:
      - "5044:5044"
    environment:
      - PATH_CONFIG=/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    networks: ['elasticstack']
    volumes:
      - "./logstash24/config/logstash.yml:/usr/share/logstash/config/logstash.yml"
      - "./logstash24/pipeline:/usr/share/logstash/pipeline"
      - "./logstash24/patterns:/usr/share/logstash/patterns"
      - "./logstash24/template:/usr/share/logstash/template"
      - "/home/gfi-dev/LIFERAY/liferay-dxp-digital-enterprise-7.0-sp4/tomcat-8.0.32/logs:/usr/share/logstash/tomcat/logs"
    command: logstash --verbose -f /usr/share/logstash/pipeline/logstash.conf

networks: {elasticstack: {}}